### PR TITLE
Fix server error

### PR DESCRIPTION
**Pull request by Tokolosh95**
Fix getting the vehicle.price

Unable to index : QBCore.Shared.Vehicles[**vehicle**]['price']

[script:qb-vehiclesho] SCRIPT ERROR: @qb-vehicleshop/server.lua:209: attempt to index a nil value (field '?')

### CODE REVIEW

**Comment by BerkieBb** [comment]
Why not remove the line altogether and just send the `buyVehicle`

**Comment by Tokolosh95** [comment]
> Why not remove the line altogether and just send the `buyVehicle`

What do you mean with "just send the buyVehicle"

**Comment by BerkieBb** [comment]
> > Why not remove the line altogether and just send the `buyVehicle`
> 
> What do you mean with "just send the buyVehicle"

Just sending that variable through the event

**Comment by Manason** [comment]
> > Why not remove the line altogether and just send the `buyVehicle`
> 
> What do you mean with "just send the buyVehicle"

Right now "vehicle" is the key within the table, but it could be the value instead as the table is not mutated and the key is only used to get to the value.

**Comment by Tokolosh95** [comment]
> > > Why not remove the line altogether and just send the `buyVehicle`
> > 
> > 
> > What do you mean with "just send the buyVehicle"
> 
> Right now "vehicle" is the key within the table, but it could be the value instead as the table is not mutated and the key is only used to get to the value.

Apologies, I am still new to this.

Do you mean make it a variable, like below.

local buyVehicle = vehicle.buyVehicle

**Pull request closed without merging**
